const CardImage = {
    HEARTS: {
        KING: "PNG\KH.png",
        QUEEN: "PNG\QH.png",
        JACK: "PNG\JH.png",
        TEN: "PNG\10H.png",
        NINE: "PNG\9H.png",
        EIGHT: "PNG\8H.png",
        SEVEN: "PNG\7H.png",
        SIX: "PNG\6H.png",
        FIVE: "PNG\5H.png",
        FOUR: "PNG\4H.png",
        THREE: "PNG\3H.png",
        TWO: "PNG\2H.png",
        ACE: "PNG\AH.png",
    },
    DIAMONDS: {
        KING: "",
        QUEEN: "",
        JACK: "",
        TEN: "",
        NINE: "",
        EIGHT: "",
        SEVEN: "",
        SIX: "",
        FIVE: "",
        FOUR: "",
        THREE: "",
        TWO: "",
        ACE: ""
    },
    CLUBS: {
        KING: "",
        QUEEN: "",
        JACK: "",
        TEN: "",
        NINE: "",
        EIGHT: "",
        SEVEN: "",
        SIX: "",
        FIVE: "",
        FOUR: "",
        THREE: "",
        TWO: "",
        ACE: ""
    },
    SPADES: {
        KING: "",
        QUEEN: "",
        JACK: "",
        TEN: "",
        NINE: "",
        EIGHT: "",
        SEVEN: "",
        SIX: "",
        FIVE: "",
        FOUR: "",
        THREE: "",
        TWO: "",
        ACE: ""
    },
}